### ISSUE TITLE
ImageMap

### ISSUE THREAD

**Issue by mudkipme** [mudkipme/52poke#19]
Moved from https://github.com/mudkipme/klinklang/issues/4

I am PikAsriel from 52Poké. Can you add the function Imagemap from mediawiki so that we can have better quality to show the picture, instead of using template?

**Comment by mudkipme** [comment]
@Asriel-cyrus 

Please demonstration a use case about displaying picture and how ImageMap extension can improve your workflow. Thanks :)

**Comment by PikAsriel** [comment]
First of all, there is a case of displaying Pokémon Mystery Dungeon maps. It is impossible for template to show a map of a variety of locations. However, Imagemap can show a variety of locations unlike using template. Secondly, if necessary, we can use imagemap instead of using a lot of images. Lastly, it is hard to use the function of magnification of templates of JavaScript and the quality is bad when magnifies the images.

In additional, user 仙子精灵 told me to ask you for her robot password (she sent the message to you in Twitter) and send the password to her email. Thank you.

**Comment by mudkipme** [comment]
ImageMap is enabled on 52Poké Wiki now.

For the bot account of @sylveon1998, as it's impossible to reset password of accounts with empty email addresses without violating the [Privacy Policy](https://wiki.52poke.com/wiki/%E7%A5%9E%E5%A5%87%E5%AE%9D%E8%B4%9D%E7%99%BE%E7%A7%91:%E9%9A%90%E7%A7%81%E6%94%BF%E7%AD%96) of 52Poké Wiki, it's recommended to register a new bot account and merge the old one into the new one.

**Comment by sylveon1998** [comment]
My register the new bot account that account name is Alice Synthesis Thirty.Please merge,Thank.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mudkip"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月27日(星期一) 中午12:39
收件人:&nbsp;"mudkipme/52poke"<52poke@noreply.github.com&gt;;
抄送:&nbsp;"妳好憂鬱"<1981763857@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [mudkipme/52poke] ImageMap (#19)




ImageMap is enabled on 52Poké Wiki now.
 
For the bot account of @sylveon1998, as it's impossible to reset password of accounts with empty email addresses without violating the Privacy Policy of 52Poké Wiki, it's recommended to register a new bot account and merge the old one into the new one.
